name: bus-orel-admin

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      BASE_URL: ${{secrets.VITE_BASE_URL}} 
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
